# Generated by Django 5.1.6 on 2025-03-01 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_Name', models.CharField(blank=True, help_text='Enter the author name', max_length=100, null=True)),
                ('Email', models.CharField(blank=True, help_text='Enter the author email', max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, help_text='Enter the author image', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='Enter the category name', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Enter a blog title', max_length=100, null=True)),
                ('Content', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Author_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.author')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
